[workspace]
resolver = "3"

[workspace.package]
authors = ["Uzair Mohammed <uzair.hamed@gmail.com>"]
repository = "https://github.com/gamersekofy/miauutils"

[workspace.dependencies]
clap = { version = "4.5.50", features = ["derive"] }
